language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
 provider: heroku
 api_key:
 secure: AfuNzri0k/os3T2FuY9mTf8ufn7/5QlWfTs/cEz0yXLxvn/jfrtyjv/ZgZAF3PmaLvGUUjhdt8rV4rinUSDmw2UZSUXxu90+uBXUvwHMGucd+V89BK6GF1B8+RG+nOv4vW2tO6hnityXZuTsLy4aorhUiJOMl9GM5R2H+B8yM8qVMAK78tD8EqFkwgSoGPOra3VnTGtPBZXicP3B3eKikNqcANp5OUWPhpLJwCRAeXTdCmcvFsJaSWYZLri1Q+YwPTOLZpxO3lc9g8XTyt40o3Um546qsRd4gp5IQ224hkLUH1aOr8IG2TFCVyq5B8ASFPBraYhFtnr9bUTQhW00BbcexZjtGOO+pTE0odPaIJdNytMG86A+eXo8b6f5vtczHu0RRaZVxteVFEMgc90Zvl9fVLeOKWqy2MEGGCL0sxa+AKxARc3C4pK85ugtMGq3NwipKRpzmR/K0KPoSmQHUShGh/pyLgQlcpVdA0Vjf8s1zOR7dbKZdUZcnKOdbgLa3PGKlx0jLZOTu9Xc9wgpXjUbu5ZFiMUzbFmfcY5UZfiD+I/T8LNmjwwzI45Ux5/2hhSSNqcg1sM9B+cVwUUy6aIbuWV8NHmg1nhQhbtLLnk/EklybFHmp9sh6qLNVohFUmgGuFAudDuZBGjHAL8E/4BQYHOZ0gbc8/wPL/G+fRo=
 app: bg-engineering-day-19

